### ISSUE TITLE
Display settings are crashing - part 1

### ISSUE THREAD

**Issue by QuinceROMs** [PixelOS-Pixelish/frameworks_base#31]
Four new refresh rate selector commits (here and in the packages_apps_Settings) cause display settings to crash. I compiled an unofficial build for OnePlus 7 (guacamoleb), where the refresh rate is 60Hz. After manually undoing them, the display settings work correctly. I am attaching a link to the log: https://logpaste.com/NJL7WXYa

https://github.com/PixelOS-AOSP/frameworks_base/commit/2aaec93237b65275199c37a841c4e8f58b46ecd8

**Comment by hridaya2004** [comment]
https://github.com/PixelOS-AOSP/packages_apps_Settings/issues/23#issuecomment-1934082273
