### ISSUE TITLE
Require unlocking to use Power options, either via QS or hardware buttons.

### ISSUE THREAD

**Issue by Ravi-Kishor** [PixelOS-Pixelish/frameworks_base#41]
Plz add Require unlocking to use Power options, either via QS or hardware buttons, it is one of the important security feature. If its already there then sry. I am on may patch and its not there.

Thank You, PixelOS Team.

**Comment by hridaya2004** [comment]
This change is already there.

You can find it here:
Security & Privacy > Device unlock > Screen lock settings > Power menu (Read it's description).
